services:
  code:
    image: king011/dev-flutter:3.16.8
    restart: always
    ports:
      # 訪問 http://127.0.0.1:9090 設置啓動 xray 更新代理等 ...
      - "9090:80/tcp"
      # 訪問 http://127.0.0.1:9000 打開 code-server 進行代碼編寫
      - "9000:8080/tcp"
    devices:
      # 將硬件映射到容器 以便  emulator 可以使用 kvm
       - /dev/kvm:/dev/kvm
    volumes:
      # 如果要使用 usb 調試 android 真實設備
      - /dev/bus:/dev/bus

      # 將 x11 映射，以便運行 gui 程式
      - /tmp/.X11-unix:/tmp/.X11-unix

      # 可選的將 android-studio 安裝到 容器
      - $HOME/volumes/flutter/android-studio:/opt/android-studio

      # 持久化 存儲 android sdk
      - $HOME/volumes/flutter/android:/opt/android
      # 持久化 存儲用戶數據
      - $HOME/volumes/flutter/home:/home/dev

      # 將本地項目目錄 掛接到容器中 
      - ./project:/home/dev/project
    environment:
      # 設置 X11
      - DISPLAY=$DISPLAY
      - BIND_ADDR=0.0.0.0:8080
      # 設置上密碼驗證，這樣即時你不在自己電腦旁邊也可以打開瀏覽器遠程開發
      - AUTH=password
      # 如果要遠程開發將密碼設置複雜點，並且推薦設置 https，這裏只是演示設置了很簡單的密碼
      - PASSWORD=123
  xray: # xray 容器用於管理網路，設置透明代理，突破朝鮮網路封鎖
    image: king011/xray-webui:v0.0.7
    restart: always
    environment:
     - XRAY_ADDR=:80
    volumes:
      # 存儲代理設定 
      - ./xray:/data
    cap_add: # 設置上這兩個特權才能在容器中使用 iptables 設置透明代理
      - NET_ADMIN
      - NET_RAW
    # 接管 code 的網路
    network_mode: service:code